### ISSUE TITLE
AKT模型的复现与原论文有差异？

### ISSUE THREAD

**Issue by RingoTC** [THUwangcy/HawkesKT#2]
您好！
您提出的HawkesKT模型让人耳目一新，关于代码仓库中对AKT模型的复现我有一些小问题。
在您复现的代码中
![image](https://user-images.githubusercontent.com/6525061/136508965-d0838ff4-3b56-41c6-a499-dc408c0c00e2.png)
question_seq只被embedding为diff_parm，但是在AKT的官方仓库中，question会被embedding为 (n_question+1, embed_l)。

期待您的回复。

**Comment by THUwangcy** [comment]
根据论文 3.4 节的描述，question 确实只贡献 diff_param，只有一个 1 维的参数，不应该有 embedding。去看了一下官方仓库，他们的 question 变量应该对应论文中的 concept，即我们代码中的 skill，他们的 pid 变量才对应 question，比较歧义的命名方式。
